yatube/about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail'
    ),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path('posts/<int:post_id>/comment', views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model


User = get_user_model()


class Group(models.Model):
    title = models.CharField(
        max_length=200,
        verbose_name='Название группы',
        help_text=(
            'Группа в которой можно'
            'опубликовать пост',
        )
    )
    slug = models.SlugField(
        unique=True,
        verbose_name='Сылочка',
        help_text='Кусок урла',
    )
    description = models.TextField(
        verbose_name='Описание',
        help_text='Описание группы',
    )

    def __str__(self):
        return str(self.slug)


class Post(models.Model):
    text = models.TextField(
        verbose_name='Текст',
        help_text='Текст для публикации',
    )
    pub_date = models.DateTimeField(
        auto_now_add=True,
        db_index=True,
        verbose_name='Дата добавления',
        help_text='Дата',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        help_text='Автор',
        verbose_name='Автор',
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        related_name='posts',
        verbose_name='Группа',
        help_text='Группа',
    )
    image = models.ImageField(
        upload_to='posts/',
        blank=True,
        verbose_name='Картинка',
        help_text='Картинка',
    )

    class Meta:
        ordering = ('-pub_date',)

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Пост',
        help_text='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор',
        help_text='Автор',
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Поле для комментария',
    )
    created = models.DateTimeField(
        verbose_name='Дата публикации',
        auto_now_add=True,
        help_text='Дата публикации',
    )

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Комментарий',

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        related_name='follower',
        on_delete=models.CASCADE,
        verbose_name='Подписчик',
        help_text='Пользователь',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
        verbose_name='Автор постов',
        help_text='Автор',
    )

    class Meta:
        verbose_name = 'Подписки',
        models.UniqueConstraint(
            fields=('user', 'aurhor',),
            name='unique_follow',
        )

    def __str__(self):
        return (f'{self.user.username} подписывается на автора '
                f'{self.author.username}')

yatube/posts/forms.py
from django import forms

from .models import Post, Comment


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.conf import settings
from django.shortcuts import redirect, render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator
from django.core.cache import cache
from .forms import PostForm, CommentForm
from .models import Group, Post, User, Follow


def index(request):
    posts_cache = cache.get('index_page')
    if posts_cache is None:
        posts_cache = Post.objects.select_related(
            'group',
            'author').order_by('-pub_date')
        cache.set('index_page', posts_cache, timeout=20)
    paginator = Paginator(posts_cache, settings.PAG_VAL)
    page_obj = paginator.get_page(request.GET.get('page'))
    context = {'posts': posts_cache, 'page_obj': page_obj}
    return render(request, 'posts/index.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    paginator = Paginator(posts, settings.PAG_VAL)
    page_obj = paginator.get_page(request.GET.get('page'))
    context = {
        'group': group,
        'posts': posts,
        'page_obj': page_obj
    }
    return render(request, 'posts/group_list.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post = author.posts.all()
    paginator = Paginator(post, settings.PAG_VAL)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    following = False
    if request.user.is_authenticated:
        following = Follow.objects.filter(
            author=author,
            user=request.user).exists()

    context = {
        'author': author,
        'posts_sum': author.posts.count(),
        'page_obj': page_obj,
        'following': following
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    posts_count = post.author.posts.count()
    form = CommentForm(request.POST or None)
    comments = post.comments.filter(post_id=post.id)
    context = {
        'post': post,
        'comments': comments,
        'post_count': posts_count,
        'form': form
    }
    return render(request, 'posts/post_detail.html', context)


@login_required
def post_create(request):
    form = PostForm(request.POST or None)
    if not form.is_valid():
        return render(request, 'posts/create_post.html', {'form': form})
    post = form.save(commit=False)
    post.author = request.user
    post.save()
    return redirect('posts:profile', username=request.user.username)


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.save()
            return redirect('posts:post_detail', post_id=post.id)
        return render(request,
                      'posts/create_post.html',
                      {'form': form},
                      )
    context = {
        'form': form,
        'post': post,
        'title': 'Редактировать пост',
        'is_edit': True
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    user = request.user
    post_list = Post.objects.filter(
        author__following__user=user)
    paginator = Paginator(post_list, settings.PAG_VAL)
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'posts': post_list, 'page_obj': page_obj}
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    if author != user:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=(author.username))


@login_required
def profile_unfollow(request, username):
    user = request.user
    author = get_object_or_404(User, username=username)
    unfollow = Follow.objects.filter(user=user, author=author)
    if unfollow.exists():
        unfollow.delete()
    return redirect('posts:profile', username=(author.username))

yatube/templates/posts/create_post.html
{% extends "base.html" %}
{% block title %}{% if is_edit %}Редактировать запись{% else %}Новый пост{% endif %}{% endblock %}
{% block header %}{% endblock %}
{% block content %}
{% load user_filters %}
<div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card shadow-sm border-dark col-md-12">
              <div class="card-header">
                {% if is_edit %}
                  Редактировать запись 
                {% else %}
                  Новый пост
                {% endif %}       
              </div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                  {% csrf_token %}
                  {% for field in form %}
                  <div class="form-group row" aria-required={{ field.field.required }}>
                    <label
                      for="{{ field.id_for_label }}"
                      class="col-md-4 col-form-label text-md-right">
                      {{ field.label }}
                      {% if field.field.required %}
                        <span class="required">*</span>
                      {% endif %}
                    </label>
                    <div class="col-md-6">
                      {{ field|addclass:"form-control" }}
                      {% if field.help_text %}
                        <small
                          id="{{ field.id_for_label }}-help"
                          class="form-text text-muted">
                          {{ field.help_text|safe }}
                        </small>
                      {% endif %}
                    </div>
                  </div>
                  {% endfor %}
                  <div class="col-md-6 offset-md-4">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>

{% endblock %}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block header %}Последние обновления на сайте{% endblock %}
{% block content %}
<br>
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
    {% include 'posts/includes/post_item.html' %}
  {% endfor %}

  {% include 'posts/includes/paginator.html' %}

{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} {{group.title}} {% endblock %}
{% block header %}{{ group }}{% endblock %}
{% block content %}
  <p>{{ group.description }}</p>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author}}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "1800x1400" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% block title %}Последние обновления на сайте{% endblock %}
{% load thumbnail %}
{% block header %}{% endblock %}
{% block content%}
{% include 'posts/includes/switcher.html' %}
{% for post in page_obj %}
   {% include 'posts/includes/post_item.html' %}
    {% if not forloop.last %}<hr>{% endif %}
   {% endfor %}
    {% include 'posts/includes/paginator.html' %}
 {% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% block title %}{{ title }}{% endblock %}
{% block header %}Пост пользователя {{ post.author }}{% endblock %}
{% block content %}
  {% include 'posts/includes/post_item.html' %}
  {% include 'posts/includes/comments.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Профиль пользователя {{ author }} {% endblock %}
{% block header %}{% endblock %}
{% block content %}
<div class="mb-5">
  <h1>Все посты пользователя {{ author }}</h1>
  <h3>Всего постов: {{ posts_sum }} </h3>
</div>
  {% for post in page_obj %}
    <ul>
      <li>
        Автор: {{ post.author}}
      </li>
      <li>
        Дата публикации: {{ post.pub_date|date:"d E Y" }}
      </li>
    </ul>
    {% thumbnail post.image "1800x1400" crop="center" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
    {% endthumbnail %}
    <p>{{ post.text }}</p>
    <a href="{% url 'posts:post_detail' post.id %}">Подробная информация</a>
    {% if post.group %}
      <a href="{% url 'posts:group_posts' post.group.slug %}">Все записи группы</a>
    {% endif %}
  <div class="mb-5">
  <h1>Все посты пользователя {{ author}}</h1>
  <h3>Всего постов: {{ posts_sum }}</h3>
  {% if following %}
    <a
      class="btn btn-lg btn-light"
      href="{% url 'posts:profile_unfollow' author.username %}" role="button"
    >
      Отписаться
    </a>
  {% else %}
      <a
        class="btn btn-lg btn-primary"
        href="{% url 'posts:profile_follow' author.username %}" role="button"
      >
        Подписаться
      </a>
   {% endif %}
</div>
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %}